import { useState, useCallback } from 'react';
import {
    FiPlus, FiTrash2, FiMail, FiSave, FiClock, FiSearch,
    FiChevronDown, FiFileText, FiX, FiCheck, FiAlertTriangle,
    FiAlertCircle, FiClipboard,
} from 'react-icons/fi';
import toast from 'react-hot-toast';
import { lookupDescription, getItemCodes, ALL_ITEMS } from '../data/masterData';

// ── Helpers ──────────────────────────────────────────────────────────────────

const STORAGE_KEY = 'pcb_challan_history';

function loadHistory() {
    try {
        return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
    } catch {
        return [];
    }
}

function saveHistory(history) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(history));
}

function calcDiff(challanQty, physicalQty) {
    const c = parseInt(challanQty, 10);
    const p = parseInt(physicalQty, 10);
    if (isNaN(c) || isNaN(p)) return null;
    return p - c;
}

function remarkFromDiff(diff) {
    if (diff === null) return '';
    if (diff === 0) return 'OK';
    if (diff > 0) return 'Excess';
    return 'Short';
}

function emptyRow() {
    return { id: Date.now() + Math.random(), itemCode: '', description: '', challanQty: '', physicalQty: '' };
}

// ── Row Status Colors ─────────────────────────────────────────────────────────

function remarkBadge(remark) {
    if (!remark) return null;
    const styles = {
        OK: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30',
        Excess: 'bg-orange-500/15 text-orange-400 border border-orange-500/30',
        Short: 'bg-red-500/15 text-red-400 border border-red-500/30',
    };
    return (
        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-semibold ${styles[remark] || ''}`}>
            {remark === 'OK' && <FiCheck className="w-3 h-3" />}
            {remark === 'Excess' && <FiAlertTriangle className="w-3 h-3" />}
            {remark === 'Short' && <FiAlertCircle className="w-3 h-3" />}
            {remark}
        </span>
    );
}

function rowBg(remark) {
    if (remark === 'OK') return 'hover:bg-emerald-500/5';
    if (remark === 'Excess') return 'hover:bg-orange-500/5';
    if (remark === 'Short') return 'hover:bg-red-500/10 bg-red-500/5';
    return 'hover:bg-surface-800/30';
}

// ── Build Email Body ──────────────────────────────────────────────────────────

function buildEmailBody(challan, rows) {
    const lines = [];
    lines.push(`PCB Verification Report`);
    lines.push(`Challan No: ${challan.challanNo}    Date: ${challan.challanDate}    Brand: ${challan.brand}`);
    lines.push('');
    lines.push('Item Code    | Description                                           | Challan Qty | Physical Qty | Difference | Remark');
    lines.push('-------------|-------------------------------------------------------|-------------|--------------|------------|-------');

    let totalChallan = 0;
    let totalPhysical = 0;

    rows.forEach((row) => {
        const diff = calcDiff(row.challanQty, row.physicalQty);
        const remark = remarkFromDiff(diff);
        const c = parseInt(row.challanQty, 10) || 0;
        const p = parseInt(row.physicalQty, 10) || 0;
        totalChallan += c;
        totalPhysical += p;
        const diffStr = diff === null ? '-' : diff > 0 ? `+${diff}` : String(diff);
        lines.push(
            `${(row.itemCode || '').padEnd(13)}| ${(row.description || '').substring(0, 53).padEnd(55)}| ${String(c).padEnd(12)}| ${String(p).padEnd(13)}| ${diffStr.padEnd(11)}| ${remark}`
        );
    });

    lines.push('-------------|-------------------------------------------------------|-------------|--------------|------------|-------');
    const totalDiff = totalPhysical - totalChallan;
    lines.push(
        `${'TOTAL'.padEnd(13)}| ${''.padEnd(55)}| ${String(totalChallan).padEnd(12)}| ${String(totalPhysical).padEnd(13)}| ${(totalDiff > 0 ? '+' : '') + totalDiff}${' '.repeat(Math.max(0, 11 - String(totalDiff).length))}|`
    );
    lines.push('');
    lines.push('Generated by PCB Tracker — Electrolyte Inventory');

    return lines.join('\n');
}

// ── History Modal ─────────────────────────────────────────────────────────────

function HistoryModal({ onClose, onLoad }) {
    const [history] = useState(loadHistory);
    const [search, setSearch] = useState('');

    const filtered = history.filter(
        (h) =>
            h.challanNo.toLowerCase().includes(search.toLowerCase()) ||
            (h.brand || '').toLowerCase().includes(search.toLowerCase())
    );

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
            <div className="animate-scale-in relative bg-surface-900 border border-surface-800 rounded-2xl shadow-2xl w-full max-w-2xl max-h-[80vh] flex flex-col">
                <div className="flex items-center justify-between p-5 border-b border-surface-800">
                    <h2 className="text-lg font-semibold text-white flex items-center gap-2">
                        <FiClock className="w-5 h-5 text-brand-400" /> Challan History
                    </h2>
                    <button onClick={onClose} className="p-2 text-surface-400 hover:text-white hover:bg-surface-800 rounded-lg transition-all cursor-pointer">
                        <FiX className="w-5 h-5" />
                    </button>
                </div>
                <div className="p-4 border-b border-surface-800">
                    <div className="relative">
                        <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-surface-500" />
                        <input
                            value={search}
                            onChange={(e) => setSearch(e.target.value)}
                            placeholder="Search by challan no. or brand..."
                            className="w-full pl-9 pr-4 py-2.5 bg-surface-800/60 border border-surface-700 text-white rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 placeholder:text-surface-500"
                        />
                    </div>
                </div>
                <div className="flex-1 overflow-y-auto p-4 space-y-2">
                    {filtered.length === 0 ? (
                        <p className="text-center text-surface-500 py-8 text-sm">No saved challans found.</p>
                    ) : (
                        filtered.map((h) => (
                            <div
                                key={h.id}
                                className="flex items-center justify-between p-3 bg-surface-800/50 border border-surface-700 rounded-xl hover:border-brand-500/40 transition-all"
                            >
                                <div>
                                    <p className="text-sm font-semibold text-white">{h.challanNo}</p>
                                    <p className="text-xs text-surface-400">{h.brand} • {h.challanDate} • {h.rows.length} item(s)</p>
                                </div>
                                <button
                                    onClick={() => { onLoad(h); onClose(); }}
                                    className="text-xs px-3 py-1.5 bg-brand-600/20 text-brand-400 border border-brand-500/30 rounded-lg hover:bg-brand-500/30 transition-all cursor-pointer"
                                >
                                    Load
                                </button>
                            </div>
                        ))
                    )}
                </div>
            </div>
        </div>
    );
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function ChallanVerification() {
    const [brand, setBrand] = useState('Bajaj');
    const [challanNo, setChallanNo] = useState('');
    const [challanDate, setChallanDate] = useState(new Date().toISOString().split('T')[0]);
    const [rows, setRows] = useState([emptyRow()]);
    const [showHistory, setShowHistory] = useState(false);
    const [emailTo, setEmailTo] = useState('');
    const [showEmailInput, setShowEmailInput] = useState(false);

    const itemCodes = getItemCodes(brand);

    // ── Row Operations ──

    const addRow = () => setRows((prev) => [...prev, emptyRow()]);

    const removeRow = (id) => setRows((prev) => prev.filter((r) => r.id !== id));

    const updateRow = useCallback((id, field, value) => {
        setRows((prev) =>
            prev.map((row) => {
                if (row.id !== id) return row;
                const updated = { ...row, [field]: value };
                // Auto-fill description when item code changes
                if (field === 'itemCode') {
                    updated.description = lookupDescription(brand, value);
                }
                return updated;
            })
        );
    }, [brand]);

    // When brand changes, re-look up all descriptions
    const handleBrandChange = (newBrand) => {
        setBrand(newBrand);
        setRows((prev) =>
            prev.map((row) => ({
                ...row,
                description: lookupDescription(newBrand, row.itemCode),
            }))
        );
    };

    // ── Totals ──

    const totalChallan = rows.reduce((s, r) => s + (parseInt(r.challanQty, 10) || 0), 0);
    const totalPhysical = rows.reduce((s, r) => s + (parseInt(r.physicalQty, 10) || 0), 0);
    const totalDiff = totalPhysical - totalChallan;

    // ── Save to History ──

    const handleSave = () => {
        if (!challanNo.trim()) { toast.error('Please enter a Challan Number.'); return; }
        const history = loadHistory();
        const entry = {
            id: Date.now(),
            brand,
            challanNo: challanNo.trim(),
            challanDate,
            rows,
            savedAt: new Date().toISOString(),
        };
        const updated = [entry, ...history.filter((h) => h.challanNo !== entry.challanNo)].slice(0, 50);
        saveHistory(updated);
        toast.success('Challan saved to history!');
    };

    // ── Load from History ──

    const handleLoad = (h) => {
        setBrand(h.brand || 'Bajaj');
        setChallanNo(h.challanNo);
        setChallanDate(h.challanDate);
        setRows(h.rows);
    };

    // ── Email ──

    const handleSendEmail = () => {
        if (!challanNo.trim()) { toast.error('Please enter a Challan Number.'); return; }
        const subject = encodeURIComponent(`PCB Verification Report - ${challanNo}`);
        const body = encodeURIComponent(buildEmailBody({ brand, challanNo, challanDate }, rows));
        const to = emailTo.trim() ? encodeURIComponent(emailTo.trim()) : '';
        window.location.href = `mailto:${to}?subject=${subject}&body=${body}`;
    };

    // ── Copy Report ──

    const handleCopyReport = async () => {
        if (!challanNo.trim()) { toast.error('Please enter a Challan Number.'); return; }
        const text = buildEmailBody({ brand, challanNo, challanDate }, rows);
        try {
            await navigator.clipboard.writeText(text);
            toast.success('Report copied to clipboard!');
        } catch {
            toast.error('Failed to copy. Please try the email option.');
        }
    };

    const inputCls = 'w-full bg-surface-800/60 border border-surface-700 text-white rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-transparent transition-all placeholder:text-surface-500';
    const selectCls = 'appearance-none w-full bg-surface-800/60 border border-surface-700 text-white rounded-xl px-3 py-2 pr-8 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 cursor-pointer';

    return (
        <>
            {showHistory && <HistoryModal onClose={() => setShowHistory(false)} onLoad={handleLoad} />}

            <div className="animate-slide-up relative overflow-hidden rounded-2xl border border-surface-800 bg-surface-900/80 backdrop-blur-sm shadow-2xl">
                {/* Accent bar */}
                <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-amber-500 via-orange-400 to-amber-500" />

                {/* Header */}
                <div className="flex items-center justify-between px-6 pt-5 pb-3">
                    <div className="flex items-center gap-2.5">
                        <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-amber-500/15">
                            <FiFileText className="w-4 h-4 text-amber-400" />
                        </div>
                        <div>
                            <h3 className="text-lg font-semibold text-white tracking-tight">Challan Verification</h3>
                            <p className="text-xs text-surface-500">Verify incoming shipment quantities</p>
                        </div>
                    </div>
                    <button
                        onClick={() => setShowHistory(true)}
                        className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-surface-300 bg-surface-800/60 border border-surface-700/50 rounded-lg hover:bg-surface-700 hover:text-white transition-all cursor-pointer"
                    >
                        <FiClock className="w-3.5 h-3.5" />
                        History
                    </button>
                </div>

                <div className="px-6 pb-6 pt-2 space-y-5">
                    {/* Shipment Info */}
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-4 bg-surface-800/30 rounded-xl border border-surface-700/50">
                        {/* Brand */}
                        <div>
                            <label className="block text-xs font-medium text-surface-400 mb-1.5">Brand</label>
                            <div className="relative">
                                <select value={brand} onChange={(e) => handleBrandChange(e.target.value)} className={selectCls}>
                                    <option value="Bajaj">Bajaj</option>
                                    <option value="Atomberg">Atomberg</option>
                                </select>
                                <FiChevronDown className="absolute right-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-surface-500 pointer-events-none" />
                            </div>
                        </div>
                        {/* Challan No */}
                        <div>
                            <label className="block text-xs font-medium text-surface-400 mb-1.5">Challan Number *</label>
                            <input
                                value={challanNo}
                                onChange={(e) => setChallanNo(e.target.value)}
                                placeholder="e.g. RC2527001175"
                                className={inputCls}
                            />
                        </div>
                        {/* Challan Date */}
                        <div>
                            <label className="block text-xs font-medium text-surface-400 mb-1.5">Challan Date</label>
                            <input
                                type="date"
                                value={challanDate}
                                onChange={(e) => setChallanDate(e.target.value)}
                                className={`${inputCls} [color-scheme:dark]`}
                            />
                        </div>
                    </div>

                    {/* PCB Items Table */}
                    <div className="overflow-x-auto rounded-xl border border-surface-700/50">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="bg-surface-800/60 text-surface-400 text-xs uppercase tracking-wider">
                                    <th className="px-3 py-2.5 text-left font-medium">Item Code</th>
                                    <th className="px-3 py-2.5 text-left font-medium">Description</th>
                                    <th className="px-3 py-2.5 text-right font-medium w-28">Challan Qty</th>
                                    <th className="px-3 py-2.5 text-right font-medium w-28">Physical Qty</th>
                                    <th className="px-3 py-2.5 text-right font-medium w-24">Difference</th>
                                    <th className="px-3 py-2.5 text-center font-medium w-24">Remark</th>
                                    <th className="px-3 py-2.5 text-center font-medium w-10"></th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-surface-800/50">
                                {rows.map((row) => {
                                    const diff = calcDiff(row.challanQty, row.physicalQty);
                                    const remark = remarkFromDiff(diff);
                                    return (
                                        <tr key={row.id} className={`transition-colors duration-150 ${rowBg(remark)}`}>
                                            {/* Item Code */}
                                            <td className="px-3 py-2">
                                                <div className="relative min-w-[120px]">
                                                    <input
                                                        list={`codes-${row.id}`}
                                                        value={row.itemCode}
                                                        onChange={(e) => updateRow(row.id, 'itemCode', e.target.value)}
                                                        placeholder="Search code..."
                                                        autoComplete="off"
                                                        className="w-full bg-surface-800/50 border border-surface-700 text-white rounded-lg px-2.5 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500/60 placeholder:text-surface-600 transition-all"
                                                    />
                                                    <datalist id={`codes-${row.id}`}>
                                                        {itemCodes.map((code) => (
                                                            <option key={code} value={code} />
                                                        ))}
                                                    </datalist>
                                                </div>
                                            </td>
                                            {/* Description */}
                                            <td className="px-3 py-2 min-w-[200px]">
                                                <input
                                                    value={row.description}
                                                    onChange={(e) => updateRow(row.id, 'description', e.target.value)}
                                                    placeholder="Auto-filled from code..."
                                                    className="w-full bg-surface-800/50 border border-surface-700 text-white rounded-lg px-2.5 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500/60 placeholder:text-surface-600 transition-all"
                                                />
                                            </td>
                                            {/* Challan Qty */}
                                            <td className="px-3 py-2">
                                                <input
                                                    type="number"
                                                    min="0"
                                                    value={row.challanQty}
                                                    onChange={(e) => updateRow(row.id, 'challanQty', e.target.value)}
                                                    placeholder="0"
                                                    className="w-full text-right bg-surface-800/50 border border-surface-700 text-white rounded-lg px-2.5 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500/60 placeholder:text-surface-600 transition-all tabular-nums"
                                                />
                                            </td>
                                            {/* Physical Qty */}
                                            <td className="px-3 py-2">
                                                <input
                                                    type="number"
                                                    min="0"
                                                    value={row.physicalQty}
                                                    onChange={(e) => updateRow(row.id, 'physicalQty', e.target.value)}
                                                    placeholder="0"
                                                    className="w-full text-right bg-surface-800/50 border border-surface-700 text-white rounded-lg px-2.5 py-1.5 text-xs focus:outline-none focus:ring-2 focus:ring-brand-500/60 placeholder:text-surface-600 transition-all tabular-nums"
                                                />
                                            </td>
                                            {/* Difference */}
                                            <td className="px-3 py-2 text-right">
                                                {diff !== null ? (
                                                    <span className={`font-semibold tabular-nums text-sm ${diff === 0 ? 'text-surface-400' : diff > 0 ? 'text-orange-400' : 'text-red-400'}`}>
                                                        {diff > 0 ? `+${diff}` : diff === 0 ? '—' : diff}
                                                    </span>
                                                ) : (
                                                    <span className="text-surface-600 text-xs">—</span>
                                                )}
                                            </td>
                                            {/* Remark */}
                                            <td className="px-3 py-2 text-center">
                                                {remarkBadge(remark)}
                                            </td>
                                            {/* Remove */}
                                            <td className="px-3 py-2 text-center">
                                                {rows.length > 1 && (
                                                    <button
                                                        onClick={() => removeRow(row.id)}
                                                        className="p-1 text-surface-600 hover:text-red-400 hover:bg-red-500/10 rounded-lg transition-all cursor-pointer"
                                                    >
                                                        <FiTrash2 className="w-3.5 h-3.5" />
                                                    </button>
                                                )}
                                            </td>
                                        </tr>
                                    );
                                })}

                                {/* Totals Row */}
                                <tr className="bg-surface-800/40 border-t-2 border-surface-700">
                                    <td colSpan={2} className="px-3 py-2.5 text-xs font-bold text-surface-300 uppercase tracking-wider">
                                        Grand Total
                                    </td>
                                    <td className="px-3 py-2.5 text-right text-sm font-bold text-white tabular-nums">
                                        {totalChallan.toLocaleString()}
                                    </td>
                                    <td className="px-3 py-2.5 text-right text-sm font-bold text-white tabular-nums">
                                        {totalPhysical.toLocaleString()}
                                    </td>
                                    <td className="px-3 py-2.5 text-right">
                                        <span className={`text-sm font-bold tabular-nums ${totalDiff === 0 ? 'text-surface-400' : totalDiff > 0 ? 'text-orange-400' : 'text-red-400'}`}>
                                            {totalDiff > 0 ? `+${totalDiff}` : totalDiff === 0 ? '—' : totalDiff}
                                        </span>
                                    </td>
                                    <td colSpan={2} />
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    {/* Add Row */}
                    <button
                        onClick={addRow}
                        className="flex items-center gap-2 text-sm text-brand-400 hover:text-brand-300 transition-colors cursor-pointer"
                    >
                        <FiPlus className="w-4 h-4" />
                        Add item row
                    </button>

                    {/* Action Buttons */}
                    <div className="flex flex-wrap gap-3 pt-1">
                        {/* Save */}
                        <button
                            onClick={handleSave}
                            className="flex items-center gap-2 px-4 py-2.5 text-sm text-white bg-brand-600 hover:bg-brand-500 rounded-xl shadow-lg shadow-brand-500/20 transition-all duration-200 cursor-pointer"
                        >
                            <FiSave className="w-4 h-4" />
                            Save Challan
                        </button>

                        {/* Copy Report */}
                        <button
                            onClick={handleCopyReport}
                            className="flex items-center gap-2 px-4 py-2.5 text-sm text-surface-200 bg-surface-800/80 border border-surface-700 rounded-xl hover:bg-surface-700 hover:text-white transition-all duration-200 cursor-pointer"
                        >
                            <FiClipboard className="w-4 h-4" />
                            Copy Report
                        </button>

                        {/* Send Email */}
                        <button
                            onClick={() => setShowEmailInput((v) => !v)}
                            className="flex items-center gap-2 px-4 py-2.5 text-sm text-surface-200 bg-surface-800/80 border border-surface-700 rounded-xl hover:bg-surface-700 hover:text-white transition-all duration-200 cursor-pointer"
                        >
                            <FiMail className="w-4 h-4" />
                            Send Email
                        </button>
                    </div>

                    {/* Email Input (toggle) */}
                    {showEmailInput && (
                        <div className="flex items-center gap-3 p-4 bg-surface-800/30 rounded-xl border border-surface-700/50 animate-slide-down">
                            <FiMail className="w-4 h-4 text-surface-400 shrink-0" />
                            <input
                                type="email"
                                value={emailTo}
                                onChange={(e) => setEmailTo(e.target.value)}
                                placeholder="recipient@example.com (optional)"
                                className={`flex-1 ${inputCls}`}
                            />
                            <button
                                onClick={handleSendEmail}
                                className="flex items-center gap-2 px-4 py-2.5 text-sm text-white bg-gradient-to-r from-brand-600 to-brand-500 hover:from-brand-500 hover:to-brand-400 rounded-xl shadow-lg shadow-brand-500/25 transition-all duration-200 whitespace-nowrap cursor-pointer"
                            >
                                <FiMail className="w-4 h-4" />
                                Open Email
                            </button>
                        </div>
                    )}
                </div>
            </div>
        </>
    );
}
